nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

changesetIgnorePatterns:
    - "**/*.test.{js,ts}"
    - "packages/*/tests/**"
    - ".yarn/cache/**"

enableGlobalCache: false

pnpEnableEsmLoader: false

immutablePatterns:
    - .pnp.*

supportedArchitectures:
    os: [darwin, linux, win32]
    cpu: [x64, arm64]

initScope: yarnpkg

npmPublishAccess: public

preferInteractive: true

telemetryUserId: yarnpkg/berry
